In [1]:
import numpy as np
import pandas as pd

In [2]:
# df = pd.DataFrame(
#     np.array(
#         [
#             ["sunny", "hot", "high", "weak", "no"],
#             ["sunny", "hot", "high", "strong", "no"],
#             ["overcast", "hot", "high", "weak", "yes"],
#             ["rain", "mild", "high", "weak", "yes"],
#             ["rain", "cool", "normal", "weak", "yes"],
#             ["rain", "cool", "normal", "strong", "no"],
#             ["overcast", "cool", "normal", "strong", "yes"],
#             ["sunny", "mild", "high", "weak", "no"],
#             ["sunny", "cool", "normal", "weak", "yes"],
#             ["rain", "mild", "normal", "weak", "yes"],
#             ["sunny", "mild", "normal", "strong", "yes"],
#             ["overcast", "mild", "high", "strong", "yes"],
#             ["overcast", "hot", "normal", "weak", "yes"],
#             ["rain", "mild", "high", "strong", "no"],
#         ],
#         dtype=object,
#     ),
#     columns=["Outlook", "Temperature", "Humidity", "Wind", "Play"],
# )
# TARGET_COLUMN = "Play"
# df_dec = df.pop(TARGET_COLUMN)

In [2]:
from sklearn.preprocessing import KBinsDiscretizer

df = pd.read_csv(
    "../../../workspace/data/microarray/anthracyclineTaxaneChemotherapy_processed.csv",
    index_col=0,
)
df_dec = df.pop("target")

est = KBinsDiscretizer(n_bins=3, encode="ordinal", strategy="quantile")
df = est.fit_transform(df)

In [4]:
# x, x_counts = prepare_factorized_array(df)
# y, y_count = prepare_factorized_vector(df_dec)

In [10]:
from skrough.algorithms.reducts import get_approx_reduct_greedy_heuristic
from skrough.chaos_measures import entropy

# get_approx_reduct_greedy_heuristic(df.to_numpy(), df_dec, 0.1, 4, entropy)
get_approx_reduct_greedy_heuristic(df, df_dec, 0.0, 100, entropy, n_reducts=1, n_jobs=1)

[AttrsSubset(attrs=[22058, 27331, 8231, 57977, 26353, 17737, 10200])]

In [6]:
# from skrough.algorithms.bireducts import get_bireduct_greedy_heuristic
# from skrough.chaos_measures import entropy

# get_bireduct_greedy_heuristic(df.to_numpy(), df_dec, 0.1, 4, entropy)

ObjsAttrsSubset(objs=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13], attrs=[0, 2, 3])

4294967296

In [47]:
import joblib
import numpy as np


def stochastic_function(seed):
    rng = np.random.default_rng(seed)
    return rng.integers(1000)


def foo(seed):
    rng = np.random.default_rng(seed)
    return joblib.Parallel(n_jobs=2)(
        joblib.delayed(stochastic_function)(None) for _ in range(10)
    )


foo(1)

[587, 777, 968, 644, 638, 779, 374, 368, 573, 536]

In [48]:
 rng = np.random.default_rng(1)
 rng.

TypeError: integers() takes at least 1 positional argument (0 given)

In [5]:
import numpy as np
from joblib import Parallel, delayed


def print_vector(vector, backend):
    """Helper function to print the generated vector with a given backend."""
    print(
        "\nThe different generated vectors using the {} backend are:\n {}".format(
            backend, np.array(vector)
        )
    )

In [7]:
def stochastic_function(max_value):
    """Randomly generate integer up to a maximum value."""
    return np.random.randint(max_value, size=5)


n_vectors = 5
random_vector = [stochastic_function(10) for _ in range(n_vectors)]
print(
    "\nThe different generated vectors in a sequential manner are:\n {}".format(
        np.array(random_vector)
    )
)


The different generated vectors in a sequential manner are:
 [[1 4 9 1 1]
 [6 6 4 5 1]
 [2 5 0 7 2]
 [9 1 5 2 7]
 [2 3 0 4 6]]


In [4]:
backend = "loky"
random_vector = Parallel(n_jobs=2, backend=backend)(
    delayed(stochastic_function)(10) for _ in range(n_vectors)
)
print_vector(random_vector, backend)

NameError: name 'Parallel' is not defined

In [10]:
backend = "threading"
random_vector = Parallel(n_jobs=2, backend=backend)(
    delayed(stochastic_function)(10) for _ in range(n_vectors)
)
print_vector(random_vector, backend)


The different generated vectors using the threading backend are:
 [[6 0 4 3 9]
 [4 1 7 1 5]
 [8 6 4 1 6]
 [9 0 9 4 7]
 [0 3 5 2 3]]


In [12]:
import multiprocessing as mp

if mp.get_start_method() == "spawn":
    import sys

    sys.exit(0)

backend = "multiprocessing"
random_vector = Parallel(n_jobs=2, backend=backend)(
    delayed(stochastic_function)(10) for _ in range(n_vectors)
)
print_vector(random_vector, backend)


The different generated vectors using the multiprocessing backend are:
 [[9 9 7 7 5]
 [9 9 7 7 5]
 [5 0 3 1 7]
 [5 0 3 1 7]
 [1 2 3 0 9]]


In [16]:
joblib.Parallel(n_jobs=1)(delayed(lambda x: x * 2)(i) for i in range(10))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [15]:
from math import modf

modf(12.35)

(0.34999999999999964, 12.0)