In [1]:
import numpy as np
import pandas as pd

In [2]:
# df = pd.DataFrame(
#     np.array(
#         [
#             ["sunny", "hot", "high", "weak", "no"],
#             ["sunny", "hot", "high", "strong", "no"],
#             ["overcast", "hot", "high", "weak", "yes"],
#             ["rain", "mild", "high", "weak", "yes"],
#             ["rain", "cool", "normal", "weak", "yes"],
#             ["rain", "cool", "normal", "strong", "no"],
#             ["overcast", "cool", "normal", "strong", "yes"],
#             ["sunny", "mild", "high", "weak", "no"],
#             ["sunny", "cool", "normal", "weak", "yes"],
#             ["rain", "mild", "normal", "weak", "yes"],
#             ["sunny", "mild", "normal", "strong", "yes"],
#             ["overcast", "mild", "high", "strong", "yes"],
#             ["overcast", "hot", "normal", "weak", "yes"],
#             ["rain", "mild", "high", "strong", "no"],
#         ],
#         dtype=object,
#     ),
#     columns=["Outlook", "Temperature", "Humidity", "Wind", "Play"],
# )
# TARGET_COLUMN = "Play"
# df_dec = df.pop(TARGET_COLUMN)

In [2]:
from sklearn.preprocessing import KBinsDiscretizer

df = pd.read_csv(
    "../../../workspace/data/microarray/anthracyclineTaxaneChemotherapy_processed.csv",
    index_col=0,
)
df_dec = df.pop("target")

est = KBinsDiscretizer(n_bins=3, encode="ordinal", strategy="quantile")
df = est.fit_transform(df)

In [4]:
# x, x_counts = prepare_factorized_array(df)
# y, y_count = prepare_factorized_vector(df_dec)

In [18]:
from skrough.algorithms.reducts import get_approx_reduct_greedy_heuristic_3
from skrough.chaos_measures import entropy

# get_approx_reduct_greedy_heuristic(df.to_numpy(), df_dec, 0.1, 4, entropy)
get_approx_reduct_greedy_heuristic_3(
    df, df_dec, 0.1, 100, entropy, n_reducts=50, n_jobs=10
)

[AttrsSubset(attrs=[43310, 3449, 1341, 60581, 58800]),
 AttrsSubset(attrs=[57402, 57554, 51569, 7352, 49476]),
 AttrsSubset(attrs=[56327, 42595, 37065, 32998, 1277]),
 AttrsSubset(attrs=[23742, 6224, 51187, 56393, 26086]),
 AttrsSubset(attrs=[10823, 22765, 14013, 51965, 50107]),
 AttrsSubset(attrs=[50782, 55207, 25688, 32792, 13439]),
 AttrsSubset(attrs=[5572, 6059, 20899, 30600, 39824, 55987]),
 AttrsSubset(attrs=[56619, 60216, 24413, 29880, 11798, 7832]),
 AttrsSubset(attrs=[22617, 42595, 53531, 32075, 44959]),
 AttrsSubset(attrs=[17344, 48302, 57385, 39827, 1371]),
 AttrsSubset(attrs=[4521, 33582, 24600, 49545, 18778]),
 AttrsSubset(attrs=[28663, 37324, 32084, 47995, 40755]),
 AttrsSubset(attrs=[23719, 26408, 10265, 9434, 28780, 4744]),
 AttrsSubset(attrs=[53384, 53879, 7813, 17166, 29780]),
 AttrsSubset(attrs=[34974, 31214, 922, 25394, 28796, 8746]),
 AttrsSubset(attrs=[55399, 18860, 60743, 865, 26472]),
 AttrsSubset(attrs=[33283, 37279, 34655, 15696, 2714, 15629]),
 AttrsSubset(at

In [3]:
from skrough.algorithms.reducts import get_approx_reduct_greedy_heuristic
from skrough.chaos_measures import entropy

# get_approx_reduct_greedy_heuristic(df.to_numpy(), df_dec, 0.1, 4, entropy)
get_approx_reduct_greedy_heuristic(df, df_dec, 0.1, 100, entropy, n_reducts=2, n_jobs=1)

[AttrsSubset(attrs=[44325, 2743, 33098, 40565, 56754]),
 AttrsSubset(attrs=[54842, 7672, 42541, 21434, 16540, 53453])]

In [6]:
# from skrough.algorithms.bireducts import get_bireduct_greedy_heuristic
# from skrough.chaos_measures import entropy

# get_bireduct_greedy_heuristic(df.to_numpy(), df_dec, 0.1, 4, entropy)

ObjsAttrsSubset(objs=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13], attrs=[0, 2, 3])

4294967296

In [47]:
import joblib
import numpy as np


def stochastic_function(seed):
    rng = np.random.default_rng(seed)
    return rng.integers(1000)


def foo(seed):
    rng = np.random.default_rng(seed)
    return joblib.Parallel(n_jobs=2)(
        joblib.delayed(stochastic_function)(None) for _ in range(10)
    )


foo(1)

[587, 777, 968, 644, 638, 779, 374, 368, 573, 536]

In [48]:
 rng = np.random.default_rng(1)
 rng.

TypeError: integers() takes at least 1 positional argument (0 given)

In [8]:
import numpy as np
from joblib import Parallel, delayed


def print_vector(vector, backend):
    """Helper function to print the generated vector with a given backend."""
    print(
        "\nThe different generated vectors using the {} backend are:\n {}".format(
            backend, np.array(vector)
        )
    )

In [4]:
def stochastic_function(max_value):
    """Randomly generate integer up to a maximum value."""
    return np.random.randint(max_value, size=5)


n_vectors = 5
random_vector = [stochastic_function(10) for _ in range(n_vectors)]
print(
    "\nThe different generated vectors in a sequential manner are:\n {}".format(
        np.array(random_vector)
    )
)


The different generated vectors in a sequential manner are:
 [[3 4 9 2 1]
 [2 4 0 4 5]
 [1 8 8 2 3]
 [2 8 8 2 6]
 [9 8 3 7 2]]


In [10]:
backend = "loky"
random_vector = Parallel(n_jobs=2, backend=backend)(
    delayed(stochastic_function)(10) for _ in range(n_vectors)
)
print_vector(random_vector, backend)


The different generated vectors using the loky backend are:
 [[3 2 8 6 4]
 [4 3 4 5 3]
 [2 3 9 2 0]
 [8 1 8 3 4]
 [0 6 4 8 5]]


In [11]:
backend = "threading"
random_vector = Parallel(n_jobs=2, backend=backend)(
    delayed(stochastic_function)(10) for _ in range(n_vectors)
)
print_vector(random_vector, backend)


The different generated vectors using the threading backend are:
 [[1 2 3 6 9]
 [6 5 4 7 6]
 [3 4 1 0 5]
 [7 3 9 9 0]
 [7 4 9 8 3]]


In [12]:
import multiprocessing as mp

if mp.get_start_method() == "spawn":
    import sys

    sys.exit(0)

backend = "multiprocessing"
random_vector = Parallel(n_jobs=2, backend=backend)(
    delayed(stochastic_function)(10) for _ in range(n_vectors)
)
print_vector(random_vector, backend)


The different generated vectors using the multiprocessing backend are:
 [[9 9 7 7 5]
 [9 9 7 7 5]
 [5 0 3 1 7]
 [5 0 3 1 7]
 [1 2 3 0 9]]


In [16]:
joblib.Parallel(n_jobs=1)(delayed(lambda x: x * 2)(i) for i in range(10))

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [15]:
from math import modf

modf(12.35)

(0.34999999999999964, 12.0)